version: 2
updates:
  # Maintain dependencies for Go Modules
  - package-ecosystem: "gomod"
    directory: "/tests"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/tests"
    target-branch: "v11.x"
    schedule:
      interval: "weekly"
    labels:
    - "v11.x"
    - "go"
    - "dependencies"
