#!/bin/bash
set -exu

function write_private_yaml() {
  set +x
  cat $PRIVATE_YML > config/private.yml
  set -x
}

function commit() {
  git config user.name "CF Syslog Bot"
  git config user.email "cf-syslog@pivotal.io"
  git add .
  git commit -m "Use current version of ${PACKAGE_NAME}" --allow-empty
}

pushd release
  write_private_yaml
  bosh vendor-package ${PACKAGE_NAME} ../package-release
  commit
popd
git clone release updated-release
