#!/bin/bash

set -e

TEST_DIR=`mktemp -d /tmp/syslog_test-$(date +%d%m%y-%H%M%S)-XXXXX`
GATEWAY_HOST=$1

bosh ssh --GATEWAY_HOST ${GATEWAY_HOST} --GATEWAY_USER vcap syslog_forwarder 0 "logger syslog-forwarder-test-msg"
bosh scp --GATEWAY_HOST ${GATEWAY_HOST} --GATEWAY_USER vcap --download syslog_storer 0 /var/vcap/store/syslog_storer/syslog.log $TEST_DIR

LOGS_FROM_FORWARDER=`cat $TEST_DIR/syslog.log.syslog_storer.* | grep 'syslog-forwarder-test-msg'`

if [ -n "$LOGS_FROM_FORWARDER" ]; then
    # there are logs from the forwarder
    echo tests succeeded
else
    # there are no logs from the forwarder
    echo tests failed

    exit 1
fi
