#!/bin/bash

set -euxo pipefail

STEMCELL_OS="${STEMCELL_OS:-ubuntu-resolute}"
INFRASTRUCTURE="${INFRASTRUCTURE:-google-kvm}"

# BPM is required on Resolute Raccoon. Older stemcells still exercise the
# non-BPM path, which exists for add-on deployments. Set USE_BPM explicitly to
# override this.
if [ -z "${USE_BPM:-}" ]; then
  case "${STEMCELL_OS}" in
    *resolute*) USE_BPM=true  ;;
    *)          USE_BPM=false ;;
  esac
fi
export USE_BPM

pushd "$(dirname "$0")/.."
  bosh create-release --force --version="$(date "+%s")"
  bosh upload-release
popd

bosh upload-release https://bosh.io/d/github.com/cloudfoundry/bpm-release
bosh upload-stemcell "https://bosh.io/d/stemcells/bosh-${INFRASTRUCTURE}-${STEMCELL_OS}"

pushd "$(dirname "$0")/../tests"
  go run github.com/onsi/ginkgo/v2/ginkgo  -r --procs="${NODES:-3}" --compilers="${NODES:-3}" --keep-going --timeout="4h" "$@"
popd
