#!/bin/bash

set -euxo pipefail

env_dir="vbox"

while getopts ":e:" opt; do
  case $opt in
    e)
      env_dir=$OPTARG;;
    :)
      echo "Usage: $0 [-e /state-dir]" >&2
      exit 1;;
  esac
done
shift $((OPTIND -1))

if [ -d "$env_dir" ]; then
  eval "$(bbl print-env --state-dir="$env_dir")"
else
  export BOSH_ENVIRONMENT=$env_dir
fi

pushd "$(dirname "$0")/../.."
  bosh create-release --force --version="$(date "+%s")"
  bosh upload-release
popd

pushd "$(dirname "$0")/.."
  go get -u -a github.com/jtarchie/syslog
  ginkgo -r "$@"
popd
